### ISSUE TITLE
Generate code for running commands manually

### ISSUE THREAD

**Issue by d-uzlov** [networkservicemesh/gotestmd#39]
# Current behavior

Currently gotestmd generates only automatic tests.
A test has requirements, the main body and a cleanup.
User is expected to run tests using `go test`.
There is no support to run custom commands without integrating them into the testing system.

# Proposal

Add commands to run the main body and cleanup as separate entities.
For example:
1. Generate test suite
2. Take a test suite A
3. We call `A.setup` and only seup commands are executed
4. Call some custom commands, which aren't a part of the original tests
5. Manually call the `A.cleanup`

The difference from current behavior is that setup and cleanup are not linked.
We can take an already generated code and integrate it into some custom program, without using the `go test`.

# Possible issues

1. What if the test relies on the fact that setup and cleanup share the same shell?
2. Would it be possible to get the same effect without changes in gotestmd code, but only using external configuration?

**Comment by NikitaSkrynnik** [comment]
Decomposition
1. Analysis - 2h 
2. ...

**Comment by denis-tingaikin** [comment]
Example of usage

 gotestmd $urll --bash

where $urll[https/http://, file:/]

output:

go suites
bash


bash example

```
function setup() {}
function cleaup(){}
tfunction test(){}
function test_cleanup(){}
```

**Comment by denis-tingaikin** [comment]
Estimation:

- add new option with cobra (example https://github.com/networkservicemesh/nsmctl) ~ 7h
-  add new template  (go-template example https://github.com/networkservicemesh/gotestmd/blob/main/internal/generator/suite.go#L28)  ~7h
- Testing~7h

**Comment by denis-tingaikin** [comment]
Seems like done
